"""AI summary of a Health record, generated by the local model in a background job and cached.

`get` returns the latest cached summary (with a `stale` flag when the record's context changed since);
`generate` queues a new one. The job publishes `spice_ai_summary` to the document's realtime room.
"""

import json
import time

import frappe
from frappe import _
from frappe.utils import add_to_date, now_datetime

from spice_facility.ai import prompts
from spice_facility.ai.config import ensure_ai_access, get_config
from spice_facility.ai.providers.base import AIProviderError
from spice_facility.ai.providers.registry import local_provider
from spice_facility.ai.summary_context import SUPPORTED, build_context, context_hash, serialise

SUMMARY = "SPICE AI Summary"
EVENT = "spice_ai_summary"
IN_FLIGHT = ("Queued", "Running")


def _check(doctype, name):
	ensure_ai_access()
	if not get_config().summary_enabled:
		frappe.throw(_("AI summaries are turned off."), frappe.ValidationError)
	if doctype not in SUPPORTED:
		frappe.throw(_("AI summaries are not available for {0}").format(doctype), frappe.ValidationError)
	frappe.has_permission(doctype, "read", doc=name, throw=True)


def _latest(doctype, name, statuses=None):
	filters = {"reference_doctype": doctype, "reference_name": name}
	if statuses:
		filters["status"] = ["in", statuses]
	rows = frappe.get_all(SUMMARY, filters, ["name", "status", "summary_json", "model", "provider", "modified",
	                                         "context_hash", "error", "duration_ms"],
	                      order_by="creation desc", limit=1)
	return rows[0] if rows else None


def _payload(row, current_hash=None):
	if not row:
		return None
	summary = row.summary_json
	if isinstance(summary, str):
		summary = json.loads(summary or "null")
	return {"name": row.name, "status": row.status, "summary": summary, "model": row.model,
	        "provider": row.provider, "generated_on": row.modified, "duration_ms": row.duration_ms,
	        "error": row.error, "stale": bool(current_hash and row.context_hash and row.context_hash != current_hash)}


@frappe.whitelist()
def get(doctype: str, name: str) -> dict:
	_check(doctype, name)
	current = context_hash(build_context(frappe.get_doc(doctype, name)))
	return {"ready": _payload(_latest(doctype, name, ["Ready"]), current),
	        "pending": _payload(_latest(doctype, name, list(IN_FLIGHT))),
	        "last_failed": _payload(_latest(doctype, name, ["Failed"]))}


def enforce_rate_limit(user=None):
	user = user or frappe.session.user
	since = add_to_date(now_datetime(), hours=-1)
	used = frappe.db.count(SUMMARY, {"requested_by": user, "creation": [">=", since]}) + frappe.db.count(
		"SPICE AI Query Log", {"user": user, "creation": [">=", since]})
	if used >= get_config().rate_limit_per_hour:
		frappe.throw(_("AI request limit reached for this hour. Please try again later."), frappe.RateLimitExceededError)


@frappe.whitelist(methods=["POST"])
def generate(doctype: str, name: str) -> dict:
	_check(doctype, name)
	pending = _latest(doctype, name, list(IN_FLIGHT))
	if pending:
		return _payload(pending)
	enforce_rate_limit()
	provider = local_provider()
	row = frappe.get_doc({"doctype": SUMMARY, "reference_doctype": doctype, "reference_name": name,
	                      "status": "Queued", "requested_by": frappe.session.user,
	                      "provider": provider.name, "model": provider.model}).insert(ignore_permissions=True)
	frappe.enqueue("spice_facility.api.ai_summary.run", queue="long", timeout=900, summary=row.name,
	               job_id=f"spice-ai-summary::{row.name}", enqueue_after_commit=True)
	return _payload(frappe._dict(row.as_dict()))


def run(summary):
	"""Background job: build context, ask the local model, store the result, notify the open form."""
	row = frappe.get_doc(SUMMARY, summary)
	row.db_set("status", "Running")
	_notify(row)
	started = time.monotonic()
	try:
		frappe.set_user(row.requested_by)
		doc = frappe.get_doc(row.reference_doctype, row.reference_name)
		context = build_context(doc)
		provider = local_provider()
		result = provider.complete_json(
			prompts.SUMMARY_SYSTEM,
			[{"role": "user", "content": "Context:\n" + serialise(context, get_config().max_context_chars)}],
			prompts.SUMMARY_SCHEMA,
		)
		result["alerts"] = merge_alerts(context.get("abnormal") or [], result.get("alerts") or [])
		row.db_set({"status": "Ready", "summary_json": json.dumps(result), "context_hash": context_hash(context),
		            "duration_ms": round((time.monotonic() - started) * 1000), "error": None})
	except (AIProviderError, frappe.ValidationError, frappe.PermissionError) as error:
		row.db_set({"status": "Failed", "error": str(error)[:500],
		            "duration_ms": round((time.monotonic() - started) * 1000)})
		frappe.log_error(title="SPICE AI summary failed", message=frappe.get_traceback())
	finally:
		frappe.set_user("Administrator")
	_notify(row)


def merge_alerts(computed, from_model):
	"""Code-computed flags are authoritative; the model may add others it saw (e.g. allergy conflicts)."""
	alerts = [{**a, "origin": "rule"} for a in computed]
	sources = [a["source"] for a in alerts]

	parameters = [(a.get("parameter") or "").lower() for a in alerts if a.get("parameter")]

	def restates_a_rule(alert):
		source, text = alert.get("source") or "", (alert.get("text") or "").lower()
		return (source.startswith("abnormal")
		        or any(source.startswith(s) or s.startswith(source) for s in sources if s and source)
		        or any(p and p in text for p in parameters))

	clinical = ("labs", "vitals", "patient.allergies", "allergies", "encounter", "history.allergies")
	alerts += [{**a, "origin": "ai"} for a in from_model
	           if not restates_a_rule(a) and (a.get("source") or "").startswith(clinical)]
	return alerts[:8]


def _notify(row):
	"""Tell the open form (document room) and the requester (user room); the block also polls as a fallback."""
	message = {"doctype": row.reference_doctype, "name": row.reference_name,
	           "status": frappe.db.get_value(SUMMARY, row.name, "status")}
	frappe.publish_realtime(EVENT, message, doctype=row.reference_doctype, docname=row.reference_name, after_commit=True)
	if row.requested_by:
		frappe.publish_realtime(EVENT, message, user=row.requested_by, after_commit=True)
